petstagram/pets/urls.py
from django.urls import path

from pets.views import list_pets, details_or_comment_pet, like_pet, edit_pet, delete_pet, create_pet, sell_pet

urlpatterns = [
    path('', list_pets, name='list pets'),
    path('detail/<int:pk>/', details_or_comment_pet, name='pet details or comment'),
    path('like/<int:pk>/', like_pet, name='like pet'),
    path('sell/<int:pk>/', sell_pet, name='sell pet'),
    path('edit/<int:pk>/', edit_pet, name='edit pet'),
    path('delete/<int:pk>/', delete_pet, name='delete pet'),
    path('create/', create_pet, name='create pet'),
]

petstagram/petstagram/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('mail/', include('mails.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
    path('', include('common.urls')),
    path('pets/', include('pets.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

petstagram/pets/models.py
from django.db import models

from accounts.models import UserProfile


class Pet(models.Model):
    DOG = 'dog'
    CAT = 'cat'
    PARROT = 'parrot'
    MOUSE = 'mouse'
    SPIDER = 'spider'
    SNAKE = 'snake'
    UNKNOWN = 'unknown'

    PET_TYPES = (
        (DOG, 'Dog'),
        (CAT, 'Cat'),
        (PARROT, 'Parrot'),
        (MOUSE, 'Mouse'),
        (SPIDER, 'Spider'),
        (SNAKE, 'Snake'),
        (UNKNOWN, 'Unknown'),
    )

    type = models.CharField(max_length=17, choices=PET_TYPES, default=UNKNOWN)
    name = models.CharField(max_length=16, blank=False)
    age = models.IntegerField(blank=False)
    description = models.TextField(blank=False)
    price = models.DecimalField(max_digits=7, decimal_places=1, blank=False)
    price_tag = '$'
    image = models.ImageField(
        upload_to='pets',
    )
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE)

    def __str__(self):
        return f'ID: {self.id} Name: {self.name} Age: {self.age} ' \
               f'Type: {self.type} Price: {self.price}{self.price_tag}'


class Like(models.Model):
    pet = models.ForeignKey(Pet, on_delete=models.CASCADE)
    test = models.CharField(max_length=2)
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE)


class Comment(models.Model):
    pet = models.ForeignKey(Pet, on_delete=models.CASCADE)
    text = models.TextField(blank=False)
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE)


class Sell(models.Model):
    pet = models.ForeignKey(Pet, on_delete=models.CASCADE)
    test = models.CharField(max_length=4)
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE)

petstagram/templates/landing_page.html
{% extends 'shared/site.html' %}
{% block site_content %}
    <div class="jumbotron parent">
        <img style="width: 100%"
             src="https://activepets.co.za/web/ap-content/uploads/2019/08/Active-pets-dogs-and-cats.png" alt="">
        <div class="absolute">
            <h1 class="display-4">Welcome to PetStore</h1>
            <p class="lead">Sell your pets. Add their photos and give them a description</p>
            <hr class="my-4">
            <div class="inner cover">
                <h1 class="cover-heading"></h1>
                <div class="row">
                    <div class="col-lg-6">
                        <p class="lead">
                            Already have an account?
                            <br>
                            <a href="{% url 'login' %}" class="btn btn-lg btn-secondary">Sign in</a>
                        </p>
                    </div>
                    <div class="col-lg-6">
                        <p class="lead"> Don't have an account? <br>
                            <a href="{% url 'signup user' %}" class="btn btn-lg btn-secondary">Sign up</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

petstagram/templates/pet_create.html
{% extends 'shared/site.html' %}
{% block site_content %}
    <h1 class="text-center">Sell new pet</h1>
    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6" align="center">
            <form method="post" class="furniture-form" enctype="multipart/form-data">
                {{ form }}
                {% csrf_token %}
                <button class="btn btn-primary mt-2" type="submit">Sell now</button>
            </form>
        </div>
        <div class="col-lg-3"></div>
    </div>
{% endblock %}

petstagram/templates/pet_delete.html
{% extends 'shared/site.html' %}
{% block site_content %}
    <div class="row">
        <div class="col-lg-12 text-center">
            <h1>Are you sure you want to delete {{ pet.name }}?</h1>
            <div class="m-auto d-flex justify-content-center">
                <div class="m-2">
                    <form method="post" action="{% url 'delete pet' pet.pk %}">
                        {% csrf_token %}
                        <button class="btn btn-danger">
                            Confirm
                        </button>
                    </form>
                </div>
                <div class="m-2">
                    <a class="btn btn-primary" href="javascript:history.back()">No, go back</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

petstagram/templates/pet_detail.html
{% extends 'shared/site.html' %}
{% block site_content %}
    <div class="d-flex">
        <div class="d-inline p-2 w-50">
            <img src="{{ pet.image.url }}"
                 class="w-50 rounded mx-auto d-block">
        </div>
        <div class="d-inline p-2 w-50">
            <div class="d-flex justify-content-between">
                <h5><u>Type:</u> {{ pet.type }}</h5>
                <h5><u>Name:</u> {{ pet.name }}</h5>
                <h5><u>Age:</u> {{ pet.age }}</h5>
                {% if pet.sell_set.count > 0 %}
                    Price: SOLD
                {% else %}
                    Price: {{ pet.price }}{{ pet.price_tag }}
                {% endif %}
            </div>
            <p class="mt-2">Description: {{ pet.description }}</p>
            <div>
                {% if can_edit %}
                    <a href="{% url 'edit pet' pet.pk %}" class="btn btn-success">Edit</a>
                {% endif %}
                {% if can_delete %}
                    <a href="{% url 'delete pet' pet.pk %}" class="btn btn-danger">Delete</a>
                {% endif %}
                {% if can_sell %}
                    {% if is_sold %}
                        <a href="{% url 'sell pet' pet.id %}"><i class="btn btn-danger" aria-hidden="true">SOLD</i></a>
                    {% else %}
                        <a href="{% url 'sell pet' pet.id %}"><i class="btn btn-success" aria-hidden="true">FOR SALE</i></a>
                    {% endif %}
                {% endif %}
            </div>
            {% if user.userprofile.mobile_number and user.userprofile.first_name and user.userprofile.last_name %}
                {% if can_like %}
                    {% if has_liked %}
                        <a href="{% url 'like pet' pet.id %}"><i class="fa fa-heart" aria-hidden="true"></i></a>
                    {% else %}
                        <a href="{% url 'like pet' pet.id %}"><i class="fa fa-heart-o" aria-hidden="true"></i></a>
                    {% endif %}
                {% endif %}
            {% endif %}
            <p class="mt-2">Likes: {{ pet.like_set.count }}</p>
        </div>
    </div>
    <div class="d-block" style="background-color: #f1e3e3; padding:2%">
        {% if pet.comment_set.all %}
            {% for comment in pet.comment_set.all %}
                <div class="box">
                    {% if comment.user.profile_picture %}
                        <img class="rounded-circle mb-3" src="{{ comment.user.profile_picture.url }}"
                             width="35" height="35"
                             alt="Unfortunately No image">
                    {% else %}
                        <img class="rounded-circle mb-3"
                             src="https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Anonymous_emblem.svg/1200px-Anonymous_emblem.svg.png"
                             width="35" height="35" alt="Generic picture">
                    {% endif %}
                    <a href="{% url 'user profile' comment.user_id %}">
                        {{ comment.user.user.username }}</a>
                    <h5><em>{{ comment.text }}</em></h5>
                    <hr>
                </div>
            {% endfor %}
        {% else %}
            <div class="box">
                <h3>There are no comments for this pet. </h3>
            </div>
        {% endif %}
        {% if user.userprofile.mobile_number and user.userprofile.first_name and user.userprofile.last_name %}
            {% if can_comment %}
                <div class="box">
                    <form method="post" action="{% url 'pet details or comment' pet.pk %}">
                        {{ form }}
                        {% csrf_token %}
                        <button class="btn btn-primary mt-2" type="submit">Add comment</button>
                    </form>
                </div>
            {% endif %}
        {% endif %}
    </div>
{% endblock %}

petstagram/templates/pet_edit.html
{% extends 'shared/site.html' %}
{% block site_content %}
    <h1 class="text-center">Edit your pets info</h1>
    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">
            <form method="post" action="{% url 'edit pet' pet.pk %}"
                  class="furniture-form"
                  enctype="multipart/form-data">
                {{ form }}
                {% csrf_token %}
                <img alt="Generic" id="img_preview" src="{{ pet.image_url }}" class="w-50 rounded mx-auto d-block"/>
                <button class="btn btn-primary mt-2" type="submit">Edit</button>
            </form>
        </div>
        <div class="col-lg-3"></div>
    </div>
    <script>
        function updateImage() {
            var img = document.getElementById('img_preview');
            var url = this.value;
            img.src = url;
        }
        document.getElementById('img_input')
            .addEventListener('input', updateImage);
    </script>
{% endblock %}

petstagram/templates/pet_list.html
{% extends 'shared/site.html' %}
{% block site_content %}
    {% if pets %}
    <h1 class='text-center'>All available pets for sale</h1>
    <div class="row">
        {% for pet in pets %}
            <div class="col-lg-4">
                <div class="card" style="width: 18rem;">
                    <img src="{{ pet.image.url }}"
                         class="card-img-top" alt="Generic picture" width="150" height="300">
                    <div class="card-body">
                        <h5 class="card-title">
                            Name: {{ pet.name }}
                            Type: {{ pet.type }}
                            Age: {{ pet.age }}
                            {% if pet.sell_set.count > 0 %}
                                Price: SOLD
                            {% else %}
                                Price: {{ pet.price }}{{ pet.price_tag }}
                            {% endif %}
                        </h5>
                        <p class="card-text">{{ pet.description }}</p>
                        <h5>
                            <u>Owner:</u>
                            <a href="{% url 'user profile' pet.user.user_id %}">{{ pet.user.user.username }}</a>
                        </h5>
                        <a href="{% url 'pet details or comment' pet.id %}" class="btn btn-info">See details</a>
                        {% if user.userprofile.mobile_number and user.userprofile.first_name and user.userprofile.last_name %}
                            {% if pet.user.user.username != user.username %}
                                <a href="{% url 'send to pet user' pet.user.user_id %}" class="btn btn-success">Send message</a>
                            {% endif %}
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    {% else %}
        <h1 class='text-center'>No available pets for sale</h1>
    {% endif %}
{% endblock %}